import React, {useState} from 'react';
import { Plus, Search, BookOpen, FilePenLine, BriefcaseBusiness, Check, CircleCheck, Circle, Pencil, Save, ChevronRight, ExternalLink, ListChecks, FileText } from 'lucide-react';
import { useOffice, PageHeading, Empty, Modal, Field, Avatar, CompanyMark, IconButton, uid, now, dueLabel, formatDate, safeUrl } from './ui.jsx';
import {useGuard, AiStatus, clone} from './helpers.jsx';

export function ExperiencesPage() {
  const {data,commit,busy}=useOffice();const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [editing,setEditing]=useState(null);
  const blank=()=>({id:uid(),title:'',category:'프로젝트',period:'',description:'',role:'',action:'',result:'',confirmed:false});
  const filtered=data.experiences.filter(e=>(filter!=='confirmed'||e.confirmed)&&(filter!=='review'||!e.confirmed)&&`${e.title} ${e.description}`.includes(query));
  return <><PageHeading eyebrow="경험 보관함" title="내 경험 보관함" description="경험을 고르면 원문과 역할·행동·결과를 함께 정리할 수 있어요." action={<button className="button primary" onClick={()=>setEditing(blank())}><Plus size={16}/> 경험 추가</button>}/>
    <div className="experience-browser">
      <div className="list-tools"><div className="tabs">{[['all','전체'],['confirmed','확인한 경험'],['review','확인 필요']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="search-box"><Search size={16}/><input aria-label="경험 검색" placeholder="경험 제목이나 내용 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
      <div className="compact-list-summary"><span>{query||filter!=='all'?'찾은 경험':'전체 경험'} {filtered.length}개</span><span>사실 확인 {data.experiences.filter(e=>e.confirmed).length} / {data.experiences.length}개</span></div>
      <ul className="compact-experience-list" aria-label="보관한 경험 목록">{filtered.map(exp=><li key={exp.id}><button type="button" className="compact-experience-row" aria-label={`${exp.title} 경험 열어보기`} onClick={()=>setEditing(clone(exp))}>
        <span className="compact-record-main"><strong>{exp.title}</strong><span className="compact-record-meta">{exp.category}<span aria-hidden="true"> · </span>{exp.period||'기간 미입력'}</span><span className="compact-record-preview">{exp.description}</span></span>
        <span className={`compact-record-status ${exp.confirmed?'confirmed':'pending'}`}>{exp.confirmed?<CircleCheck size={14}/>:<Circle size={14}/>} {exp.confirmed?'사실 확인됨':'확인 필요'}</span><ChevronRight className="compact-record-arrow" size={17} aria-hidden="true"/>
      </button></li>)}</ul>
      {!filtered.length&&(data.experiences.length?<Empty icon={Search} title="조건에 맞는 경험이 없어요" action={<button className="button" onClick={()=>{setQuery('');setFilter('all');}}>검색 · 필터 초기화</button>}>검색어나 확인 상태를 바꿔보세요. 저장한 경험은 그대로 보관되어 있어요.</Empty>:<Empty icon={BookOpen} title="어떤 경험부터 꺼내볼까요?" action={<button className="button primary" onClick={()=>setEditing(blank())}><Plus size={15}/> 경험 등록하기</button>}>정리해 둔 메모를 그대로 붙여넣어도 좋아요.</Empty>)}
    </div>{editing&&<ExperienceModal experience={editing} onClose={()=>setEditing(null)} onSave={async form=>{const ok=await commit(s=>{const i=s.experiences.findIndex(e=>e.id===form.id);const saved={...form,updatedAt:now()};if(i<0)s.experiences.unshift(saved);else s.experiences[i]=saved;},'경험을 보관했어요');if(ok)setEditing(null);}} busy={busy}/>}</>;
}
function ExperienceModal({experience,onClose,onSave,busy,inline=false}) {
  const [form,setForm]=useState(experience);const set=(k,v)=>setForm(s=>({...s,[k]:v}));const dirty=JSON.stringify(form)!==JSON.stringify(experience);useGuard(dirty);
  const close=()=>{if(dirty&&!confirm('저장하지 않은 경험 내용이 있어요. 닫을까요?'))return;onClose();};
  const Container=inline?InlineExperiencePanel:Modal;
  return <Container title="내 경험 정리하기" wide onClose={close}><form onSubmit={e=>{e.preventDefault();onSave(form);}}><Field label="경험 제목"><input required maxLength={160} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="예: 동아리 행사 참여 경험 개선"/></Field><div className="form-row"><Field label="경험 종류"><select value={form.category} onChange={e=>set('category',e.target.value)}>{['프로젝트','동아리','인턴·경력','수업','개인 활동','기타'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="기간"><input value={form.period} maxLength={100} onChange={e=>set('period',e.target.value)} placeholder="예: 2025.03 – 2025.06"/></Field></div><Field label="내가 정리한 원문" hint="기존 메모를 그대로 넣어주세요. 사실에 없는 성과는 채우지 않아도 됩니다."><textarea required rows={5} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="어떤 상황에서 무엇을 했는지 적어주세요."/></Field><div className="form-row"><Field label="내 역할"><textarea rows={3} value={form.role} onChange={e=>set('role',e.target.value)} placeholder="내가 맡은 부분은 무엇이었나요?"/></Field><Field label="내가 한 행동"><textarea rows={3} value={form.action} onChange={e=>set('action',e.target.value)} placeholder="문제를 해결하기 위해 무엇을 했나요?"/></Field></div><Field label="결과 또는 배운 점"><textarea rows={3} value={form.result} onChange={e=>set('result',e.target.value)} placeholder="숫자가 없어도 괜찮아요. 확인할 수 있는 변화를 적어주세요."/></Field><label className="check-label"><input type="checkbox" checked={form.confirmed} onChange={e=>set('confirmed',e.target.checked)}/>내가 실제로 한 일인지 확인했어요.</label><div className="form-footer"><button className="button" type="button" onClick={close}>취소</button><button className="button primary" disabled={busy} type="submit"><Save size={15}/> 경험 저장</button></div></form></Container>;
}

export function JobsPage() {
  const {data,selectedJob,setSelectedJob,commit,busy,navigate,workspace}=useOffice();const [editing,setEditing]=useState(null);const [query,setQuery]=useState('');
  const job=data.jobs.find(j=>j.id===selectedJob);
  const blank=()=>({id:uid(),company:'',role:'',type:'신입',deadline:'',url:'',body:'',requirements:'',stage:'saved',color:'green',createdAt:now()});
  const filtered=data.jobs.filter(j=>`${j.company} ${j.role}`.includes(query));
  return <><PageHeading eyebrow="관심 공고" title="관심 공고" description="공고를 모으고, 어떤 경험을 보여줄지 차근차근 살펴봐요." action={<button className="button primary" onClick={()=>setEditing(blank())}><Plus size={16}/> 공고 등록</button>}/><div className="jobs-workflow">{!job&&<section className="record-list job-library"><div className="search-box"><Search size={16}/><input aria-label="공고 검색" placeholder="회사나 직무 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="record-count">보관한 공고 {data.jobs.length}개</div>{filtered.map(j=><button key={j.id} className={`record-item ${job?.id===j.id?'selected':''}`} onClick={()=>setSelectedJob(j.id)}><CompanyMark job={j}/><div><small>{j.company}</small><strong>{j.role}</strong><span>{j.type} · {dueLabel(j.deadline)}</span></div><ChevronRight size={15}/></button>)}{!filtered.length&&<div className="small-empty">{query?'검색한 공고가 없어요.':'아직 공고가 없어요.'}</div>}</section>}{job?<section className="detail-card"><button className="text-button library-back" onClick={()=>setSelectedJob(null)}>← 전체 공고 목록</button><div className="detail-heading"><div><div className="company-name">{job.company}{workspace==='demo'&&<span className="sample-label">가상 자료</span>}</div><h2>{job.role}</h2><div className="detail-tags"><span className="pill">{job.type}</span><span className="due">{dueLabel(job.deadline)}</span><span className="meta">{formatDate(job.deadline)} 마감</span></div></div><IconButton label="공고 수정" onClick={()=>setEditing(clone(job))}><Pencil size={18}/></IconButton></div><div className="detail-section"><h3><FileText size={17}/> 공고 원문</h3><p className="source-text">{job.body || '아직 공고 본문이 없어요. 공고 수정을 눌러 내용을 붙여넣어 주세요.'}</p>{safeUrl(job.url)&&<a className="text-button" target="_blank" rel="noreferrer" href={job.url}>원문 열기 <ExternalLink size={13}/></a>}</div><div className="detail-section"><h3><ListChecks size={17}/> 내가 정리한 핵심 조건 <span className="pill muted">직접 정리</span></h3>{job.requirements?<ul className="requirement-list">{job.requirements.split('\n').filter(Boolean).map((r,i)=><li key={i}><Check size={14}/>{r}</li>)}</ul>:<p className="muted-copy">공고에서 중요한 조건을 골라 직접 적어보세요.</p>}</div><AiStatus>AI 공고 분석은 연결 전이에요. 등록한 원문과 정리한 조건은 보관됩니다.</AiStatus><div className="action-row"><button className="button primary" onClick={()=>navigate('essays',job.id)}><FilePenLine size={16}/> 이 공고로 자소서 준비</button><button className="button" onClick={()=>setEditing(clone(job))}><Pencil size={15}/> 조건 정리하기</button></div></section>:!data.jobs.length?<Empty icon={BriefcaseBusiness} title="첫 공고를 가져와 보세요" action={<button className="button primary" onClick={()=>setEditing(blank())}>공고 등록하기</button>}>회사·직무와 공고 본문을 붙여넣으면 준비를 시작할 수 있어요.</Empty>:null}</div>{editing&&<JobModal job={editing} busy={busy} onClose={()=>setEditing(null)} onSave={async form=>{const ok=await commit(s=>{const i=s.jobs.findIndex(j=>j.id===form.id);if(i<0)s.jobs.unshift(form);else s.jobs[i]=form;},'공고를 보관했어요');if(ok){setSelectedJob(form.id);setEditing(null);}}}/>}</>;
}
export function JobModal({job,onClose,onSave,busy}) {
  const [form,setForm]=useState(job);const set=(k,v)=>setForm(s=>({...s,[k]:v}));const dirty=JSON.stringify(form)!==JSON.stringify(job);useGuard(dirty);
  const close=()=>{if(dirty&&!confirm('저장하지 않은 공고 내용이 있어요. 닫을까요?'))return;onClose();};
  return <Modal title="공고 보관하기" wide onClose={close}><form onSubmit={e=>{e.preventDefault();onSave(form);}}><div className="form-row"><Field label="회사"><input required maxLength={150} value={form.company} onChange={e=>set('company',e.target.value)} placeholder="회사 이름"/></Field><Field label="직무"><input required maxLength={150} value={form.role} onChange={e=>set('role',e.target.value)} placeholder="지원할 직무"/></Field></div><div className="form-row"><Field label="채용 구분"><select value={form.type} onChange={e=>set('type',e.target.value)}>{['신입','인턴','경력','무관'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="마감일" hint="날짜를 모르면 비워두세요."><input type="date" value={form.deadline} onChange={e=>set('deadline',e.target.value)}/></Field></div><Field label="공고 주소"><input type="url" value={form.url} onChange={e=>set('url',e.target.value)} placeholder="https://…"/></Field><Field label="공고 본문" hint="본문을 직접 붙여넣거나 수정할 수 있어요. 주소로 가져오려면 공고 목록의 링크로 등록을 사용해 주세요."><textarea rows={7} value={form.body} onChange={e=>set('body',e.target.value)} placeholder="담당 업무, 필수 자격, 우대 사항을 붙여넣어 주세요."/></Field><Field label="내가 정리한 핵심 조건" hint="한 줄에 하나씩 적어주세요. AI 분석 결과와 구분해 보관합니다."><textarea rows={3} value={form.requirements} onChange={e=>set('requirements',e.target.value)} placeholder="예: 고객 의견을 바탕으로 개선안을 만든 경험"/></Field><div className="form-footer"><button className="button" type="button" onClick={close}>취소</button><button className="button primary" type="submit" disabled={busy}><Save size={15}/> 공고 저장</button></div></form></Modal>;
}

function InlineExperiencePanel({children}) {return <section className="card experience-entry">{children}</section>;}
export function NewExperiencePage() {
  const {commit,busy,navigate,setDirty}=useOffice();
  const [blank]=useState(()=>({id:uid(),title:'',category:'프로젝트',period:'',description:'',role:'',action:'',result:'',confirmed:false}));
  const leave=()=>{setDirty(false);navigate('experiences');};
  return <><PageHeading eyebrow="경험 보관함" title="새 경험 정리하기" description="정리해 둔 내용을 바로 적어 주세요. 저장하면 경험 보관함에 모입니다."/><ExperienceModal inline experience={blank} busy={busy} onClose={leave} onSave={async form=>{const ok=await commit(s=>s.experiences.unshift({...form,updatedAt:now()}),'경험을 보관했어요');if(ok)leave();}}/></>;
}
