import React,{useEffect,useState} from 'react';
import {Save,Plug,BriefcaseBusiness,Compass,Copy,ExternalLink,Download} from 'lucide-react';
import {useOffice,PageHeading,Notice,Modal,Field,uid,now,dateToday,formatDate} from './ui.jsx';
import {useGuard,AiStatus} from './helpers.jsx';
import {GeminiConnection} from './gemini.jsx';
import {ProfileEditor} from './profile.jsx';
import {normalizeProfile} from '../lib/profile.mjs';
const promptStages=['공고 분석','경험 선택','글 구성','초안 작성','퇴고','방향성 안내'];

export function SettingsPage() {
  const {data,commit,busy,notify,workspace,runtime}=useOffice();const [tab,setTab]=useState('profile');const [profile,setProfile]=useState(()=>normalizeProfile(data.profile));const [stage,setStage]=useState('초안 작성');const [promptText,setPromptText]=useState('');const [promptName,setPromptName]=useState('');const [restore,setRestore]=useState(null);const [tokenCopied,setTokenCopied]=useState(false);
  const active=data.prompts.filter(p=>p.stage===stage&&p.active).at(-1);const promptList=data.prompts.filter(p=>p.stage===stage);
  useEffect(()=>{setPromptText(active?.content||'');setPromptName(active?.name||'');},[stage,active?.id]);
  const dirty=tab==='profile'?JSON.stringify(profile)!==JSON.stringify(normalizeProfile(data.profile)):tab==='prompts'?(promptText!==(active?.content||'')||promptName!==(active?.name||'')):false;useGuard(dirty);
  const exportData=()=>{const blob=new Blob([JSON.stringify({format:'moa-office-backup',version:1,workspace,exportedAt:now(),data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`moa-${workspace}-${dateToday()}-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);notify('백업 파일을 내려받았어요');};
  return <><PageHeading eyebrow="나에게 맞게" title="내 정보 · 설정" description="내 자료와 작업 방식을 차근차근 준비해요."/><div className="settings-tabs tabs">{[['profile','내 기본 정보'],['prompts','내 프롬프트'],['connections','연결 상태'],['backup','자료 보관']].map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>{if(dirty&&!confirm('저장하지 않은 내용이 있어요. 다른 설정을 열까요?'))return;setTab(key);}}>{label}</button>)}</div>
    {tab==='profile'&&<ProfileEditor profile={profile} onChange={setProfile} busy={busy} dirty={dirty} onSave={()=>commit(s=>{s.profile=profile;},'기본 정보를 저장했어요')}/>} 
    {tab==='prompts'&&<div className="prompt-layout"><section className="card"><h2>단계별 지시문</h2><p className="helper">직접 준비한 프롬프트를 등록하세요. 수정할 때마다 새 버전으로 남습니다.</p><Field label="작업 단계"><select value={stage} onChange={e=>{if(dirty&&!confirm('저장하지 않은 프롬프트를 남기고 단계를 바꿀까요?'))return;setStage(e.target.value);}}>{promptStages.map(s=><option key={s}>{s}</option>)}</select></Field><form onSubmit={async e=>{e.preventDefault();await commit(s=>{s.prompts.filter(p=>p.stage===stage).forEach(p=>p.active=false);s.prompts.push({id:uid(),stage,name:promptName,content:promptText,version:promptList.length+1,active:true,createdAt:now()});},'프롬프트를 새 버전으로 저장했어요');}}><Field label="프롬프트 이름"><input required value={promptName} onChange={e=>setPromptName(e.target.value)} placeholder="예: 경험 근거를 먼저 확인하는 초안"/></Field><Field label="프롬프트 내용"><textarea required rows={13} value={promptText} onChange={e=>setPromptText(e.target.value)} placeholder="이 단계에서 AI가 무엇을 어떻게 도와주면 좋을지 적어주세요."/></Field><div className="form-footer"><button className="button primary" disabled={busy}><Save size={15}/> 새 버전으로 저장</button></div></form></section><aside className="card"><h3>저장한 버전</h3>{promptList.length?[...promptList].reverse().map(p=><div className="prompt-version" key={p.id}><div><strong>v{p.version} · {p.name}</strong><small>{formatDate(p.createdAt)} 저장</small></div>{p.active?<span className="pill">사용 중</span>:<button className="text-button" disabled={busy} onClick={async()=>{if(dirty&&!confirm('저장하지 않은 프롬프트가 있어요. 이 버전을 사용할까요?'))return;await commit(s=>{s.prompts.filter(x=>x.stage===stage).forEach(x=>x.active=x.id===p.id);},'사용할 버전을 바꿨어요');}}>사용하기</button>}</div>):<p className="helper">이 단계에 등록된 프롬프트가 없어요.</p>}<AiStatus>프롬프트 저장은 AI 실행이 아닙니다. 자소서 화면에서 요청문을 준비해 복사할 수 있어요.</AiStatus></aside></div>}
    {tab==='connections'&&<div className="connection-grid"><GeminiConnection/>{runtime?.extensionMode==='local-only'?<section className="card"><h2>Chrome 확장 프로그램</h2><p>확장 프로그램은 이 컴퓨터에서 실행한 사무실에 연결해 사용해 주세요. 첫 온라인 버전에서는 확장 연결을 제공하지 않습니다.</p></section>:<section className="card"><div className="connection-head"><span className="connection-icon"><BriefcaseBusiness size={23}/></span><span className="pill amber">입력 보조 v0.2</span></div><h2>Chrome 확장 프로그램</h2><p>저장한 학력·자격증 등을 고르고 지원서의 빈 입력란에 채웁니다. 현대오토에버를 첫 대상으로 준비했으며, 로그인 후 실제 양식의 호환성은 확인 중입니다.</p><div className="connection-actions"><a className="button" href="/autofill-test.html" target="_blank" rel="noreferrer">자동 입력 시험 화면 <ExternalLink size={14}/></a><button className="button soft" onClick={async()=>{try{const r=await fetch('/api/extension-token');if(!r.ok)throw Error();const b=await r.json();await navigator.clipboard.writeText(b.token);setTokenCopied(true);notify('확장 프로그램 연결 코드를 복사했어요');}catch{notify('연결 코드 복사에 실패했어요');}}}><Copy size={14}/> {tokenCopied?'연결 코드 다시 복사':'연결 코드 복사'}</button></div><small className="helper">프로젝트의 extension 폴더를 Chrome에 설치해 주세요. 확장에서 개인/샘플 자료를 선택할 수 있어요. 기존 입력값과 자소서는 유지하고, 저장·제출 버튼은 누르지 않습니다.</small></section>}<section className="card"><div className="connection-head"><Compass size={23}/><span className="pill muted">아직 실행 안 함</span></div><h2>정기 공고 수집</h2><p>수집 대상과 접근 방식이 검증된 뒤 연결합니다. 지금은 직접 보관한 공고만 방향성 노트에 표시됩니다.</p></section></div>}
    {tab==='backup'&&<section className="settings-card card"><h2>내 자료 보관</h2><Notice>현재 {workspace==='demo'?'샘플 체험':'개인 사무실'}의 자료만 내보내거나 복원합니다. 두 공간은 분리되어 있습니다.</Notice><div className="backup-row"><div><h3>파일로 백업하기</h3><p>경험·공고·자소서 버전·프롬프트·지원 내역을 함께 저장합니다.</p></div><button className="button" onClick={exportData}><Download size={16}/> 내보내기</button></div><div className="backup-row"><div><h3>백업 파일 확인하기</h3><p>현재 자료를 바꾸기 전, 불러올 파일의 내용을 먼저 확인합니다.</p><input aria-label="백업 파일 선택" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>4_000_000)throw Error('파일이 너무 큽니다.');const b=JSON.parse(await file.text());if(b.format!=='moa-office-backup'||b.version!==1||!b.data||!Array.isArray(b.data.jobs)||!Array.isArray(b.data.experiences)||!Array.isArray(b.data.essays)||!Array.isArray(b.data.prompts)||!Array.isArray(b.data.applications))throw Error('모아 백업 파일이 아닙니다.');setRestore(b);}catch(error){notify(error.message);}e.target.value='';}}/></div></div><div className="backup-row"><div><h3>움직임 줄이기</h3><p>버튼과 상태 표시의 움직임을 줄입니다.</p></div><label className="check-label"><input type="checkbox" checked={data.preferences.reducedMotion} onChange={e=>commit(s=>{s.preferences.reducedMotion=e.target.checked;},'화면 설정을 저장했어요')}/>사용</label></div><p className="helper">{runtime?.deployment==='cloud'?'자료는 연결된 Supabase 온라인 저장소에 보관합니다. 내보내기로 별도 백업을 남길 수 있습니다. 홈 화면의 할 일은 현재 브라우저에만 저장됩니다.':runtime?'자료는 이 컴퓨터의 SQLite 파일에 저장합니다. 브라우저의 방문 기록을 지워도 사무실 자료는 유지되지만, 프로젝트의 .data 폴더를 지우면 사라질 수 있어요.':'저장 위치를 확인하고 있습니다. 중요한 자료는 내보내기로 별도 백업해 주세요.'}</p></section>}
    {restore&&<Modal title="백업 자료 확인" onClose={()=>setRestore(null)}><p className="muted-copy">경험 {restore.data.experiences.length}건 · 공고 {restore.data.jobs.length}건 · 자소서 {restore.data.essays.length}건</p><Notice>복원하면 현재 {workspace==='demo'?'샘플':'개인'} 공간의 자료를 바꿉니다. 먼저 현재 자료를 백업해 주세요.</Notice><div className="form-footer"><button className="button" onClick={exportData}>현재 자료 백업</button><button className="button primary" disabled={busy} onClick={async()=>{if(!confirm('선택한 백업으로 현재 공간의 자료를 바꿀까요?'))return;const ok=await commit(s=>{Object.keys(s).forEach(k=>delete s[k]);Object.assign(s,restore.data);},'백업 자료를 복원했어요');if(ok){setRestore(null);setProfile(normalizeProfile(restore.data.profile));}}}>이 자료로 복원</button></div></Modal>}</>;
}
