import React,{useState} from 'react';
import {RequirementChart} from './requirement-chart.jsx';
import {Plus,ClipboardList,Pencil,Save,Compass,ChevronRight} from 'lucide-react';
import {useOffice,PageHeading,Notice,Empty,Modal,Field,IconButton,Avatar,uid,now,dateToday,formatDate} from './ui.jsx';
import {useGuard,clone} from './helpers.jsx';

export function ApplicationsPage() {
  const {data,commit,busy}=useOffice();const [editing,setEditing]=useState(null);const [filter,setFilter]=useState('전체');
  const statuses=['지원 완료','확인 필요','제출 실패','서류 검토 중','면접','합격','불합격','지원 취소'];
  const list=data.applications.filter(a=>filter==='전체'||a.status===filter);
  const completed=data.applications.filter(a=>['지원 완료','서류 검토 중','면접','합격','불합격'].includes(a.status)).length;
  const add=()=>setEditing({id:uid(),company:'',role:'',appliedAt:dateToday(),status:'지원 완료',source:'직접 확인',note:''});
  return <><PageHeading eyebrow="지원 현황" title="지원 관리" description="어디에, 어떤 직무로, 언제 지원했는지 한눈에 살펴봐요." action={<button className="button primary" onClick={add}><Plus size={16}/> 지원 기록</button>}/><div className="stat-row"><div><span>전체 기록</span><strong>{data.applications.length}<small>건</small></strong></div><div><span>제출한 지원</span><strong>{completed}<small>건</small></strong></div><div><span>직접 확인 필요</span><strong>{data.applications.filter(a=>a.status==='확인 필요').length}<small>건</small></strong></div></div><Notice>초기 버전에서는 직접 확인한 지원을 기록합니다. 확장 프로그램의 자동 감지는 로컬 시험 페이지에서만 지원하며, 실제 채용 사이트는 아직 검증 전입니다.</Notice><div className="list-tools"><div className="tabs">{['전체','지원 완료','확인 필요','면접'].map(x=><button className={filter===x?'selected':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{list.length?<div className="table-wrap"><table><thead><tr><th>회사 · 직무</th><th>지원일</th><th>상태</th><th>확인 출처</th><th><span className="sr-only">수정</span></th></tr></thead><tbody>{list.map(a=><tr key={a.id}><td><strong>{a.company}</strong><small>{a.role}</small></td><td>{a.appliedAt?formatDate(a.appliedAt):'확인 필요'}</td><td><span className={`record-status ${a.status==='지원 완료'?'confirmed':''}`}>{a.status}</span></td><td><span className="meta">{a.source}</span></td><td><IconButton label={`${a.company} 지원 기록 수정`} onClick={()=>setEditing(clone(a))}><Pencil size={16}/></IconButton></td></tr>)}</tbody></table></div>:<Empty icon={ClipboardList} title="첫 지원을 기록해 볼까요?" action={<button className="button primary" onClick={add}>지원 내역 추가</button>}>회사, 직무, 지원일만 적으면 돼요. 자기소개서는 수집하지 않습니다.</Empty>}{editing&&<ApplicationModal record={editing} statuses={statuses} jobs={data.jobs} busy={busy} onClose={()=>setEditing(null)} onSave={async record=>{const duplicate=data.applications.find(a=>a.id!==record.id&&a.company===record.company&&a.role===record.role&&a.appliedAt===record.appliedAt);if(duplicate&&!confirm('같은 회사·직무·날짜의 기록이 있어요. 별도 지원으로 추가할까요?'))return;const ok=await commit(s=>{const i=s.applications.findIndex(a=>a.id===record.id);const saved={...record,source:'직접 확인',updatedAt:now()};if(i<0)s.applications.unshift(saved);else s.applications[i]=saved;},'지원 기록을 저장했어요');if(ok)setEditing(null);}}/>}</>;
}
function ApplicationModal({record,statuses,jobs,busy,onClose,onSave}) {
  const [form,setForm]=useState(record);const [confirmed,setConfirmed]=useState(false);const set=(k,v)=>setForm(s=>({...s,[k]:v}));const dirty=JSON.stringify(form)!==JSON.stringify(record);useGuard(dirty);
  const close=()=>{if(dirty&&!confirm('저장 전 변경사항이 있어요. 닫을까요?'))return;onClose();};
  return <Modal title="지원 내역 기록" onClose={close}><form onSubmit={e=>{e.preventDefault();if(form.status==='지원 완료'&&!confirmed)return;onSave(form);}}>{jobs.length>0&&<Field label="보관한 공고에서 선택 (선택 사항)"><select value={form.jobId||''} onChange={e=>{const job=jobs.find(j=>j.id===e.target.value);if(job)setForm({...form,jobId:job.id,company:job.company,role:job.role});else setForm({...form,jobId:''});}}><option value="">직접 입력</option>{jobs.map(j=><option value={j.id} key={j.id}>{j.company} · {j.role}</option>)}</select></Field>}<div className="form-row"><Field label="회사"><input required maxLength={150} value={form.company} onChange={e=>set('company',e.target.value)}/></Field><Field label="직무"><input required maxLength={150} value={form.role} onChange={e=>set('role',e.target.value)}/></Field></div><div className="form-row"><Field label="지원일"><input type="date" required={form.status==='지원 완료'} value={form.appliedAt} onChange={e=>set('appliedAt',e.target.value)}/></Field><Field label="지원 상태"><select value={form.status} onChange={e=>{set('status',e.target.value);setConfirmed(false);}}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field></div>{form.status==='지원 완료'&&<label className="check-label"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>실제 접수 완료를 확인했어요. 버튼을 누르기만 한 상태가 아닙니다.</label>}<div className="form-footer"><button type="button" className="button" onClick={close}>취소</button><button type="submit" className="button primary" disabled={busy||(form.status==='지원 완료'&&!confirmed)}><Save size={15}/> 지원 기록 저장</button></div></form></Modal>;
}
export function DirectionPage() {
  const {data,navigate}=useOffice();const [role,setRole]=useState('전체');const roles=[...new Set(data.jobs.map(j=>j.role))];const jobs=data.jobs.filter(j=>role==='전체'||j.role===role);
  const needsRole=data.experiences.filter(e=>!e.role);const needsResult=data.experiences.filter(e=>!e.result);const unconfirmed=data.experiences.filter(e=>!e.confirmed);
  return <><PageHeading eyebrow="방향성 노트" title="다음 한 걸음 찾기" description="점수 대신, 무엇을 더 구체적으로 보여줄지 살펴봐요."/><div className="direction-scope"><div><Compass size={25}/><div><strong>{role==='전체'?'보관한 공고 기준':role}</strong><span>내가 보관한 공고와 경험만 살펴봅니다.</span></div></div><select aria-label="방향성 공고 직무" value={role} onChange={e=>setRole(e.target.value)}><option>전체</option>{roles.map(r=><option key={r}>{r}</option>)}</select></div><Notice>이 화면은 입력한 조건의 단순 집계와 빈 항목 점검입니다. AI 역량 분석이나 시장 전체의 경향이 아니며, 같은 뜻의 다른 표현은 합치지 않습니다.</Notice><div className="direction-grid"><section className="card"><div className="section-title"><h2>공고에서 정리한 조건</h2><span className="pill">{jobs.length}개 공고</span></div><RequirementChart jobs={jobs}/><button className="text-button" onClick={()=>navigate('jobs')}>공고 확인하기 <ChevronRight size={14}/></button></section><section className="card"><div className="section-title"><h2>경험을 더 선명하게</h2><Avatar type="squirrel" size={33}/></div><div className="next-action"><span className="step-number">01</span><div><strong>내 역할을 적어보세요</strong><p>{!data.experiences.length?'경험을 먼저 등록해 주세요.':needsRole.length?`${needsRole.length}건에 역할 정보가 비어 있어요.`:'모든 경험에 내 역할이 적혀 있어요.'}</p></div></div><div className="next-action"><span className="step-number">02</span><div><strong>행동 이후의 변화를 확인해요</strong><p>{!data.experiences.length?'활동 이후의 변화나 배운 점을 적어보세요.':needsResult.length?`${needsResult.length}건에 결과 또는 배운 점이 비어 있어요.`:'모든 경험에 결과가 적혀 있어요.'}</p></div></div><div className="next-action"><span className="step-number">03</span><div><strong>실제로 한 일인지 확인해요</strong><p>{!data.experiences.length?'등록한 내용이 사실인지 직접 확인합니다.':unconfirmed.length?`${unconfirmed.length}건이 사실 확인을 기다리고 있어요.`:'등록한 경험의 사실 확인을 마쳤어요.'}</p></div></div><button className="button soft full" onClick={()=>navigate('experiences')}>내 경험 보완하기</button></section></div><div className="direction-note"><Avatar type="owl" size={55}/><div><h3>기록에 없다고, 능력이 없는 건 아니에요.</h3><p>아직 꺼내놓지 않은 이야기가 있을 수 있어요. 정기 공고 수집과 AI 기반 보완 제안은 다음 연결 단계에서 추가합니다.</p></div></div></>;
}
